language: csharp
dist: trusty
sudo: true

os:
  - linux
  - osx

mono:
  - latest
  - 5.0.1

install:

script: ./mono/build-mono.sh && ./mono/test-mono.sh

#  allow_failures:
#    - os: osx
#      mono: latest
